### ISSUE TITLE
Use heroes metadata API

### ISSUE THREAD

**Issue by leamare** [justinkohlenberg/meta-to-grid#1]
Yo!
I noticed you're hardcoded hero IDs/names into the script, which might be a painful experience once the game changes every now and then.

My API isn't very well documented (duh), but here's a `metadata` mod that can return some specific metadata.
Including heroes data: https://stats.spectral.gg/lrg2/api/?mod=metadata&gets=heroes&pretty

It has a slightly different format from what's used in your code, but I might be easy enough to transform. Metadata is updated ASAP so it should be always up to date with the reports.

**Comment by justinkohlenberg** [comment]
Hey,

Thanks for that tip, I'll look into applying it.
It would indeed be painful if new heroes are introduced, so the current
hardcode stuff is the first thing I wanted to improve upon.

Cool that you stumbled on this script though, from the reddit thread I
assume?

Op zo 29 aug. 2021 22:29 schreef Lea Silakov ***@***.***>:

**Comment by leamare** [comment]
Yes! A friend linked me your comment on the thread.

**Comment by justinkohlenberg** [comment]
Cool, if you have any issues with me crawling your page every once in a
while just let me know.

Op ma 30 aug. 2021 00:34 schreef Lea Silakov ***@***.***>:

**Comment by justinkohlenberg** [comment]
Fixed in the latest commit e8cf13ff558c9880fbe30d9ac47f5ac2aac52294
